### ISSUE TITLE
Add the prod Hypermedia API to Flex

### ISSUE THREAD

**Issue by hmgibson23** [guardian/tagmanager#128]
Need to do this once we have a CNAME

**Comment by clloyd** [comment]
@hmgibson23 Looking at the flex PR this is already done?

**Comment by hmgibson23** [comment]
I think so

On 9 February 2016 at 16:10, Christopher Lloyd <notifications@github.com>
wrote:

> @hmgibson23 <https://github.com/hmgibson23> Looking at the flex PR this
> is already done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/tagmanager/issues/128#issuecomment-181932948>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
