### ISSUE TITLE
Changes to the top bar and add favicon

### ISSUE THREAD

**Issue by akemitakagi** [guardian/tagmanager#135]
@clloyd 
Please 
1) Add favicon
2) Add 'tag' icon on the top left. (this is a link back to tags home)
3) Add highlight blue borer on the top of the navigation when it's selected.

Please see the image below.
The icon and favicon are attached in the email yesterday.

![tagmanager-topbar-06](https://cloud.githubusercontent.com/assets/5967941/12813169/43cae77e-cb2e-11e5-9145-c2bbb50ffd59.png)

**Comment by clloyd** [comment]
![fav-tag-16](https://cloud.githubusercontent.com/assets/551573/12914562/e219f84c-cf1c-11e5-833f-d7db35228a86.png)
![fav-tag-32](https://cloud.githubusercontent.com/assets/551573/12914564/e21b96c0-cf1c-11e5-8458-d7812b0dddc4.png)
![fav-tag-64](https://cloud.githubusercontent.com/assets/551573/12914563/e219e596-cf1c-11e5-9386-8c7fe079aa3e.png)
![fav-tag-128](https://cloud.githubusercontent.com/assets/551573/12914565/e21e0b4e-cf1c-11e5-8cde-4b0c6b94a200.png)

**Comment by clloyd** [comment]
[Assets.zip](https://github.com/guardian/tagmanager/files/122955/Assets.zip)
